@echo off
echo Installing Flask...
pip install flask
echo Installing Zhipuai...
pip install zhipuai
echo Running app.py...
python app.py
echo Opening browser...
start http://127.0.0.1:5000
echo Done.
pause